language: python
python:
- '3.5'
node_js:
- '7'
services:
- mongodb
env:
  global:
  - DJANGO=1.8
  - PYTHON=python3.5
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$VIRTUAL_ENV/lib/$PYTHON/site-packages"
  - "$TRAVIS_BUILD_DIR/kaizen/kaizen-front/node_modules"
before_install:
- ls -a ~/.ssh/
- openssl aes-256-cbc -K $encrypted_9bd931470e1c_key -iv $encrypted_9bd931470e1c_iv -in kdt_rsa.enc -out ~/.ssh/kdt_rsa -d
- openssl aes-256-cbc -K $encrypted_8c4ba12eb40a_key -iv $encrypted_8c4ba12eb40a_iv -in config.py.enc -out $TRAVIS_BUILD_DIR/kaizen/kaizen/config.py -d
- chmod 600 ~/.ssh/kdt_rsa
- pip install -U pip
install:
- pip install -r requirements.txt
before_script:
- cd kaizen/kaizen-front/
- npm install
script:
- npm run build
- python $TRAVIS_BUILD_DIR/kaizen/manage.py migrate

after_success:
- scp -r $TRAVIS_BUILD_DIR/kaizen/account root@106.14.134.47:~/
- ssh root@106.14.134.47 "~/Project-Kaizen/kaizen/prepareBackend.sh"
- echo "build and deploy successfully!"
branches:
  only:
  - deploy
addons:
  ssh_known_hosts: 106.14.134.47
